### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by SwannSchilling** [jorgejgnz/HandTrackingPack-HapticFeedback#1]
I am getting the following build error : Object reference is not set to an instance of an object
I noticed missing scripts at LeftHandAnchor and RightHandAnchor...
Also whenever I am pressing the play button in the editor, Unity crashes!!

**Comment by jorgejgnz** [comment]
The build error was caused by a bug in Oculus Android package. This package has been updated to 1.3.6 and AndroidManifest.xml has been regenerated.
There was a script that wasn't been pushed but now it is included.
I've pushed these fixes. I hope it works for you now.

Thank you so much for informing about the error!

**Comment by SwannSchilling** [comment]
Hey, thanks for the Update, I will try to build the new version!
I am building a 1:1 room mapping with game objects replacing the room objects...still struggling a bit with calibration and really like the way you did the tables surface!

The play button crashing Unity is a bug with handtracking and the editor at the moment, if the Oculus is in sleep mode it will crash Unity...hopefully this will get fixed soon!
